# Generated by Django 5.1.2 on 2024-10-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('language', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru')], default='uz', max_length=2)),
            ],
        ),
    ]
