TEXTS = {
    'bilingual': {
        'subscribe_channels': "Botdan foydalanish uchun quyidagi kanallarga obuna bo'ling! 👇\n\n"
                            "Подпишитесь на следующие каналы, чтобы использовать бота! 👇",
        'not_subscribed': "Siz quyidagi kanal(lar)ga obuna bo'lmagansiz! ❌\n\n"
                         "Вы не подписаны на следующий канал(ы)! ❌",
        'check_subscription': "Obunani tekshirish 🔄 Проверить подписку",
        'choose_language': "Tilni tanlang 👇\n\nВыберите язык 👇",
    },
    'uz': {
        'subscribed_all': "✅ Siz hamma kanalga a'zo bo'lgansiz!\n\nEndi botdan foydalanish uchun tilni tanlang 👇",
        'main_menu': "Botdan foydalanish uchun kerakli bo'limni tanlang! 👇",
        'language_select': "Tilni tanlang:",
        'type_select': "E'lon turini tanlang:",
        "employee": {
            "skills": "Ko'nikmalaringizni kiriting:",
            "firm_name": "Firma nomini kiriting:",
            "activity": "Faoliyatni kiriting:",
            "contact_person": "Ma'sul ismingizni kiriting:",
            "phone": "Telefon raqamingizni kiriting:",
            "region": "Hududingizni kiriting:",
            "contact_time": "Murojaat vaqtini kiriting:",
            "work_time": "Ish vaqtini kiriting:",
            "salary": "Maoshni kiriting:",
            "additional": "Qo'shimchalarni kiriting:",
        },
        "job": {
            "name": "Ismingizni kiriting:",
            "age": "Yoshingizni kiriting:",
            "profession": "Kasbingizni kiriting:",
            "experience": "Stajingizni kiriting:",
            "phone": "Telefon raqamingizni kiriting:",
            "region": "Hududingizni kiriting:",
            "expected_salary": "Kutayotgan oyligingizni kiriting:",
            "additional": "Qo'shimchalarni kiriting:",
        },
        "partner": {
            "name": "Ismingizni kiriting:",
            "activity_type": "Faoliyat turingizni kiriting:",
            "region": "Hududingizni kiriting:",
            "phone": "Telefon raqamingizni kiriting:",
            "additional": "Qo'shimchalarni kiriting:",
        },
        "error":"Xato ma'lumot kiritdingiz",
        "data_cancelled":"Qaytadan ma'lumot kiriting ",
        "admin_aprov":"Sizning e'loningiz Adminga yuborildi.\nTasdiqlangandan so'ng sizga xabar beriladi.",
    },
    'ru': {
        'subscribed_all': "✅ Вы подписаны на все каналы!\n\nТеперь выберите язык для использования бота 👇",
        'main_menu': "Выберите нужный раздел для использования бота! 👇",
        'language_select': "Выберите язык:",
        'type_select': "Выберите тип объявления:",
        "employee": {
            "skills": "Введите ваши навыки:",
            "firm_name": "Введите название фирмы:",
            "activity": "Введите деятельность:",
            "contact_person": "Введите имя ответственного лица:",
            "phone": "Введите ваш номер телефона:",
            "region": "Введите ваш регион:",
            "contact_time": "Введите время для связи:",
            "work_time": "Введите рабочее время:",
            "salary": "Введите зарплату:",
            "additional": "Введите дополнительные сведения:",
        },
        "job": {
            "name": "Введите ваше имя:",
            "age": "Введите ваш возраст:",
            "profession": "Введите вашу профессию:",
            "experience": "Введите ваш стаж:",
            "phone": "Введите ваш номер телефона:",
            "region": "Введите ваш регион:",
            "expected_salary": "Введите ожидаемую зарплату:",
            "additional": "Введите дополнительные сведения:",
        },
        "partner": {
            "name": "Введите ваше имя:",
            "activity_type": "Введите вид деятельности:",
            "region": "Введите ваш регион:",
            "phone": "Введите ваш номер телефона:",
            "additional": "Введите дополнительные сведения:",
        },
        "error":"Вы ввели неверную информацию",
        "data_cancelled":"Введите информацию еще раз",
        "admin_aprov":"Ваше объявление отправлено Администратору.\nВы получите уведомление после подтверждения.",
    }
}
